apiVersion: v1
kind: Service
metadata:
  name: {{ include "keydb-multimaster.fullname" . }}
spec:
  selector:
    app: {{ include "keydb-multimaster.name" . }}
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  type: ClusterIP
