apiVersion: v1
kind: Service
metadata:
  name: {{ include "keydb-multimaster.fullname" . }}
spec:
  selector:
    app: {{ include "keydb-multimaster.name" . }}
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  type: ClusterIP
ec2-user@[astrokure-eks-dev::keydb-uat][~/custom-keydb/KeyDB/my-keydb-chart/templates]> cat statefulset.yaml 
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "keydb-multimaster.fullname" . }}
spec:
  serviceName: {{ include "keydb-multimaster.fullname" . }}-headless
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "keydb-multimaster.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "keydb-multimaster.name" . }}
    spec:
      containers:
        - name: keydb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args: ["/etc/keydb/keydb.conf"]
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: config
              mountPath: /etc/keydb
            - name: data
              mountPath: /data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "keydb-multimaster.fullname" . }}-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{- end }}
