apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keydb-mesh.fullname" . }}-config
data:
  keydb.conf.template: |
    bind 0.0.0.0
    port 6379
    requirepass {{ .Values.keydb.requirepass }}
    multi-master yes
    active-replica yes
    protected-mode yes
    appendonly yes
    appendfsync everysec
    replica-read-only no
    maxclients 10000
    maxmemory-policy allkeys-lru
    tcp-backlog 511
    timeout 0
    tcp-keepalive 300
    repl-backlog-size 256mb
    repl-timeout 60
    repl-disable-tcp-nodelay no
    client-output-buffer-limit normal 0 0 0
    client-output-buffer-limit replica 256mb 64mb 60
    client-output-buffer-limit pubsub 32mb 8mb 60
    dir /data
