apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "keydb-multimaster.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "keydb-multimaster.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: {{ include "keydb-multimaster.fullname" . }}-headless
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "keydb-multimaster.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: keydb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["keydb-server", "/etc/keydb/keydb.conf"]
          ports:
            - containerPort: 6379
              name: redis
          env:
            - name: REDISCLI_AUTH
              valueFrom:
                secretKeyRef:
                  name: keydb-auth
                  key: password
          volumeMounts:
            - name: config
              mountPath: /etc/keydb/
              subPath: keydb.conf
            - name: data
              mountPath: /data
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "keydb-cli -a {{ .Values.keydb.requirepass }} -p 6379 ping | grep PONG"
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "keydb-cli -a {{ .Values.keydb.requirepass }} -p 6379 info replication | grep -q 'master_repl_offset:[1-9]'"
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      initContainers:
        - name: config-init
          image: busybox
          command:
            - sh
            - -c
            - |
              index=$(echo $POD_NAME | awk -F'-' '{print $NF}')
              cp /config/keydb.conf.template /config/keydb.conf
              for i in $(seq 0 $((REPLICA_COUNT - 1))); do
                if [ "$i" != "$index" ]; then
                  echo "replicaof {{ .Release.Name }}-$i.{{ .Release.Name }}-headless.{{ .Release.Namespace }}.svc.cluster.local 6379" >> /config/keydb.conf
                fi
              done
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: REPLICA_COUNT
              value: "{{ .Values.replicaCount }}"
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

